--Create below tables as per following data
--STU_INFO
--Rno Name Branch
--101 RAJU CE
--102 AMIT CE
--103 SANJAY ME
--104 NEHA EC
--105 MEERA EE
--106 MAHESH ME

           CREATE TABLE STU_INFO (
              RNO INT,
              NAME VARCHAR(50),
              BRANCH VARCHAR(50) );

           INSERT INTO STU_INFO(RNO,NAME,BRANCH) VALUES(101,'RAJU','CE')
           INSERT INTO STU_INFO(RNO,NAME,BRANCH) VALUES(102,'AMIT','CE')
           INSERT INTO STU_INFO(RNO,NAME,BRANCH) VALUES(103,'SANJAY','ME')
           INSERT INTO STU_INFO(RNO,NAME,BRANCH) VALUES(104,'NEHA','EC')
           INSERT INTO STU_INFO(RNO,NAME,BRANCH) VALUES(105,'MEERA','EE')
           INSERT INTO STU_INFO(RNO,NAME,BRANCH) VALUES(106,'MAHESH','ME')
                SELECT * FROM STU_INFO

--RESULT
-- Rno SPI
--101 8.8
--102 9.2
--103 7.6
--104 8.2
--105 7.0
--107 8.9

            CREATE TABLE RESULT (
                RNO INT,
                SPI DECIMAL(4,2) );

            INSERT INTO RESULT(RNO,SPI) VALUES(101,8.8)
            INSERT INTO RESULT(RNO,SPI) VALUES(102,9.2)
            INSERT INTO RESULT(RNO,SPI) VALUES(103,7.6)
            INSERT INTO RESULT(RNO,SPI) VALUES(104,8.2)
            INSERT INTO RESULT(RNO,SPI) VALUES(105,7.0)
            INSERT INTO RESULT(RNO,SPI) VALUES(107,8.9)
                  SELECT * FROM RESULT

--EMPLOYEE_MASTER
--EmployeeNo Name ManagerNo
--E01 TARUN NULL
--E02 ROHAN E02
--E03 PRIYA E01
--E04 MILAN E03
--E05 JAY E01
--E06 ANJANA E04
            
            CREATE TABLE EMPLOYEE_MASTER1 (
               EMPLOYEENO VARCHAR(50),
               NAME VARCHAR(50),
               MANAGERNO VARCHAR(50) );

            INSERT INTO EMPLOYEE_MASTER1(EMPLOYEENO,NAME,MANAGERNO) VALUES ('E01','TARUN','NULL')
            INSERT INTO EMPLOYEE_MASTER1(EMPLOYEENO,NAME,MANAGERNO) VALUES ('E02','ROHAN','E02')
            INSERT INTO EMPLOYEE_MASTER1(EMPLOYEENO,NAME,MANAGERNO) VALUES ('E03','PRIYA','E01')
            INSERT INTO EMPLOYEE_MASTER1(EMPLOYEENO,NAME,MANAGERNO) VALUES ('E04','MILAN','E03')
            INSERT INTO EMPLOYEE_MASTER1(EMPLOYEENO,NAME,MANAGERNO) VALUES ('E05','JAY','E01')
            INSERT INTO EMPLOYEE_MASTER1(EMPLOYEENO,NAME,MANAGERNO) VALUES ('E06','ANJANA','E04')
                      SELECT * FROM EMPLOYEE_MASTER1

--Part – A:
--1.Combine information from student and result table using cross join or Cartesian product.
    SELECT * FROM STU_INFO CROSS JOIN RESULT
--2.Perform inner join on Student and Result tables.
    SELECT * FROM STU_INFO INNER JOIN RESULT ON STU_INFO.RNO = RESULT.RNO
--3.Perform the left outer join on Student and Result tables.
    SELECT * FROM STU_INFO LEFT OUTER JOIN RESULT ON STU_INFO.RNO = RESULT.RNO
--4.Perform the right outer join on Student and Result tables.
    SELECT * FROM STU_INFO RIGHT OUTER JOIN RESULT ON STU_INFO.RNO = RESULT.RNO
--5.Perform the full outer join on Student and Result tables.
    SELECT * FROM STU_INFO FULL OUTER JOIN RESULT ON STU_INFO.RNO = RESULT.RNO
--6.Display Rno, Name, Branch and SPI of all students.
    SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STU_INFO S , RESULT R WHERE S.RNO = R.RNO
--7.Display Rno, Name, Branch and SPI of CE branch’s student only.
    SELECT STU_INFO.RNO,STU_INFO.NAME,STU_INFO.BRANCH,RESULT.SPI FROM STU_INFO JOIN RESULT ON STU_INFO.RNO = RESULT.RNO WHERE STU_INFO.BRANCH = 'CE'
--8.Display Rno, Name, Branch and SPI of other than EC branch’s student only.
    SELECT STU_INFO.RNO,STU_INFO.NAME,STU_INFO.BRANCH,RESULT.SPI FROM STU_INFO JOIN RESULT ON STU_INFO.RNO = RESULT.RNO WHERE STU_INFO.BRANCH != 'EC'
--9.Display average result of each branch.
    SELECT BRANCH,AVG(SPI) FROM STU_INFO JOIN RESULT ON STU_INFO.RNO = RESULT.RNO GROUP BY BRANCH
--10.Display average result of CE and ME branch.
    SELECT BRANCH,AVG(SPI) FROM STU_INFO JOIN RESULT ON STU_INFO.RNO = RESULT.RNO WHERE BRANCH IN ('CE','ME') GROUP BY BRANCH
--11.Display Maximum and Minimum SPI of each branch.
     SELECT BRANCH,MAX(SPI),MIN(SPI) FROM STU_INFO JOIN RESULT ON STU_INFO.RNO = RESULT.RNO GROUP BY BRANCH
--12.Display branch wise student’s count in descending order.
     SELECT BRANCH,COUNT(BRANCH) FROM STU_INFO JOIN RESULT ON STU_INFO.RNO = RESULT.RNO GROUP BY BRANCH ORDER BY COUNT(BRANCH) DESC

--Part – B:
--1.Display average result of each branch and sort them in ascending order by SPI.
    SELECT BRANCH,AVG(SPI) FROM STU_INFO JOIN RESULT ON STU_INFO.RNO = RESULT.RNO GROUP BY BRANCH ORDER BY AVG(SPI)
--2.Display highest SPI from each branch and sort them in descending order.
    SELECT BRANCH,MAX(SPI) FROM STU_INFO JOIN RESULT ON STU_INFO.RNO = RESULT.RNO GROUP BY BRANCH ORDER BY MAX(SPI) DESC

--Part – C:
--1.Retrieve the names of employee along with their manager’s name from the Employee table.
    SELECT E.EMPLOYEENO, E.NAME AS EMPNAME,M.NAME AS MNGNAME FROM EMPLOYEE_MASTER1 E LEFT JOIN EMPLOYEE_MASTER1 M ON E.MANAGERNO = M.EMPLOYEENO