--Create following table (Using Design Mode) PERSON 
--Column_Name DataType Constraints
--PersonID Int Primary Key
--PersonName Varchar (100) Not Null
--DepartmentID Int Foreign Key, Null
--Salary Decimal (8,2) Not Null
--JoiningDate Datetime Not Null
--City Varchar (100) Not Null

                       CREATE TABLE PERSON (
                          PERSONID INT PRIMARY KEY,
                          PERSONNAME VARCHAR(100) NOT NULL,
                          DEPARTMENTID INT NULL,
                          SALARY DECIMAL(8,2) NOT NULL,
                          JOINNINGDATE DATETIME NOT NULL,
                          CITY VARCHAR(100) NOT NULL,
                          FOREIGN KEY (DEPARTMENTID) REFERENCES DEPT(DEPARTMENTID) );

--PersonID PersonName DepartmentID Salary JoiningDate City
--101 Rahul Tripathi 2 56000 01-01-2000 Rajkot
--102 Hardik Pandya 3 18000 25-09-2001 Ahmedabad
--103 Bhavin Kanani 4 25000 14-05-2000 Baroda
--104 Bhoomi Vaishnav 1 39000 08-02-2005 Rajkot
--105 Rohit Topiya 2 17000 23-07-2001 Jamnagar
--106 Priya Menpara NULL 9000 18-10-2000 Ahmedabad
--107 Neha Sharma 2 34000 25-12-2002 Rajkot
--108 Nayan Goswami 3 25000 01-07-2001 Rajkot
--109 Mehul Bhundiya 4 13500 09-01-2005 Baroda
--110 Mohit Maru 5 14000 25-05-2000 Jamnagar

INSERT INTO PERSON(PERSONID,PERSONNAME,DEPARTMENTID,SALARY,JOINNINGDATE,CITY) VALUES (101,'RAHUL TRIPATHI',2,56000,'2000-01-01','RAJKOT')
INSERT INTO PERSON(PERSONID,PERSONNAME,DEPARTMENTID,SALARY,JOINNINGDATE,CITY) VALUES (102,'HARDIK PANDYA',3,18000,'2001-09-25','AHMEDABAD')
INSERT INTO PERSON(PERSONID,PERSONNAME,DEPARTMENTID,SALARY,JOINNINGDATE,CITY) VALUES (103,'BHAVIN KANANI',4,25000,'2000-05-14','BARODA')
INSERT INTO PERSON(PERSONID,PERSONNAME,DEPARTMENTID,SALARY,JOINNINGDATE,CITY) VALUES (104,'BHOOMI VAISHNAV',1,39000,'2005-02-08','RAJKOT')
INSERT INTO PERSON(PERSONID,PERSONNAME,DEPARTMENTID,SALARY,JOINNINGDATE,CITY) VALUES (105,'ROHIT TOPIYA',2,17000,'2001-07-23','JAMNAGAR')
INSERT INTO PERSON(PERSONID,PERSONNAME,DEPARTMENTID,SALARY,JOINNINGDATE,CITY) VALUES (106,'PRIYA MENPARA',NULL,9000,'2000-10-18','AHMEDABAD')
INSERT INTO PERSON(PERSONID,PERSONNAME,DEPARTMENTID,SALARY,JOINNINGDATE,CITY) VALUES (107,'NEHA SHARMA',2,34000,'2002-12-25','RAJKOT')
INSERT INTO PERSON(PERSONID,PERSONNAME,DEPARTMENTID,SALARY,JOINNINGDATE,CITY) VALUES (108,'NAYAN GOSWAMI',3,25000,'2001-07-01','RAJKOT')
INSERT INTO PERSON(PERSONID,PERSONNAME,DEPARTMENTID,SALARY,JOINNINGDATE,CITY) VALUES (109,'MEHUL BHUNDIYA',4,13500,'2005-01-09','BARODA')
INSERT INTO PERSON(PERSONID,PERSONNAME,DEPARTMENTID,SALARY,JOINNINGDATE,CITY) VALUES (110,'MOHIT MARU',5,14000,'2000-05-25','JAMNAGAR')
            SELECT * FROM PERSON

--DEPT 
--Column_Name DataType Constraints
--DepartmentID Int Primary Key
--DepartmentName Varchar (100) Not Null, Unique
--DepartmentCode Varchar (50) Not Null, Unique
--Location Varchar (50) Not Null

                      CREATE TABLE DEPT (
                         DEPARTMENTID INT PRIMARY KEY,
                         DEPARTMENTNAME VARCHAR(100) NOT NULL UNIQUE,
                         DEPARTMENTCODE VARCHAR(50) NOT NULL UNIQUE,
                         LOCATION VARCHAR(50) NOT NULL );
                         DROP TABLE DEPT

--DepartmentID DepartmentName DepartmentCode Location
--1 Admin Adm A-Block
--2 Computer CE C-Block
--3 Civil CI G-Block
--4 Electrical EE E-Block
--5 Mechanical ME B-Block

INSERT INTO DEPT(DEPARTMENTID,DEPARTMENTNAME,DEPARTMENTCODE,LOCATION) VALUES (1,'ADMIN','ADM','A-BLOCK')
INSERT INTO DEPT(DEPARTMENTID,DEPARTMENTNAME,DEPARTMENTCODE,LOCATION) VALUES (2,'COMPUTER','CE','C-BLOCK')
INSERT INTO DEPT(DEPARTMENTID,DEPARTMENTNAME,DEPARTMENTCODE,LOCATION) VALUES (3,'CIVIL','CI','G-BLOCK')
INSERT INTO DEPT(DEPARTMENTID,DEPARTMENTNAME,DEPARTMENTCODE,LOCATION) VALUES (4,'ELECTRICAL','EE','E-BLOCK')
INSERT INTO DEPT(DEPARTMENTID,DEPARTMENTNAME,DEPARTMENTCODE,LOCATION) VALUES (5,'MECHANICAL','ME','B-BLOCK')
          SELECT * FROM DEPT

--From the above given table perform the following queries:
--Part – A:
--1.Combine information from Person and Department table using cross join or Cartesian product.
    SELECT * FROM PERSON CROSS JOIN DEPT
--2.Find all persons with their department name
    SELECT PERSONNAME,DEPARTMENTNAME FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID
--3.Find all persons with their department name & code.
    SELECT PERSONNAME,DEPARTMENTNAME,DEPARTMENTCODE FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID
--4.Find all persons with their department code and location.
    SELECT PERSONNAME,DEPARTMENTCODE,LOCATION FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID
--5.Find the detail of the person who belongs to Mechanical department.
    SELECT PERSON. * FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID WHERE DEPARTMENTNAME = 'MECHANICAL'
--6.Final person’s name, department code and salary who lives in Ahmedabad city.
    SELECT PERSONNAME,DEPARTMENTCODE,SALARY FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID WHERE CITY = 'AHMEDABAD'
--7.Find the person's name whose department is in C-Block.
    SELECT PERSONNAME FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID WHERE LOCATION = 'C-BLOCK' 
--8.Retrieve person name, salary & department name who belongs to Jamnagar city.
    SELECT PERSONNAME,SALARY,DEPARTMENTNAME FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID WHERE CITY = 'JAMNAGAR'
--9.Retrieve person’s detail who joined the Civil department after 1-Aug-2001.
    SELECT PERSON.* FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID WHERE DEPARTMENTNAME = 'CIVIL' AND JOINNINGDATE > '2001-08-01'
--10.Display all the person's name with the department whose joining date difference with the current date is more than 365 days.
    SELECT PERSONNAME,DEPARTMENTNAME FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID WHERE DATEDIFF(DAY,JOINNINGDATE,GETDATE()) > 365
--11.Find department wise person counts.
    SELECT DEPARTMENTNAME,COUNT(PERSONNAME) AS PERSONCOUNT FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID GROUP BY DEPT.DEPARTMENTNAME
--12.Give department wise maximum & minimum salary with department name.
    SELECT DEPARTMENTNAME,MAX(SALARY) AS MAX_SAL,MIN(SALARY) AS MIN_SAL FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID GROUP BY DEPT.DEPARTMENTNAME
--13.Find city wise total, average, maximum and minimum salary.
    SELECT CITY,SUM(SALARY) AS TOT_SAL,AVG(SALARY) AS AVG_SAL,MAX(SALARY) AS MAX_SAL,MIN(SALARY) AS MIN_SAL FROM PERSON GROUP BY CITY
--14.Find the average salary of a person who belongs to Ahmedabad city.
    SELECT AVG(SALARY) AS AVG_SAL FROM PERSON WHERE CITY = 'AHMEDABAD'
--15.Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. (In single column)
    SELECT PERSONNAME + ' LIVES IN ' + CITY + ' AND WORKS IN ' + DEPARTMENTNAME + ' DEPARTMENT.' AS INFO FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID

--Part – B:
--1.Produce Output Like: <PersonName> earns <Salary> from <DepartmentName> department monthly. (In single column)
   SELECT PERSONNAME + ' EARNS ' + CAST(SALARY AS VARCHAR) + ' FROM ' + DEPARTMENTNAME + ' DEPARTMENT MONTHLY.' AS INFORMATION FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID
--2.Find city & department wise total, average & maximum salaries.
   SELECT CITY,DEPARTMENTNAME, SUM(SALARY) AS SUM_SAL,AVG(SALARY) AS AVG_SAL,MAX(SALARY) AS MAX_SAL FROM PERSON JOIN DEPT  ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID  GROUP BY CITY,DEPARTMENTNAME
--3.Find all persons who do not belong to any department.
   SELECT * FROM PERSON  WHERE DEPARTMENTID IS NULL
--4.Find all departments whose total salary is exceeding 100000.
   SELECT DEPARTMENTNAME,SUM(SALARY) AS TOT_SAL FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID GROUP BY DEPARTMENTNAME HAVING SUM(SALARY) > 100000

--Part – C:
--1.List all departments who have no person.
   SELECT DEPARTMENTNAME FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID WHERE PERSONID IS NULL
--2.List out department names in which more than two persons are working.
   SELECT DEPARTMENTNAME,COUNT(PERSONID) AS PERSONCOUNT FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID GROUP BY DEPARTMENTNAME HAVING COUNT(PERSONID) > 2
--3.Give a 10% increment in the computer department employee’s salary. (Use Update)
   UPDATE PERSON SET SALARY  = SALARY * 1.1 FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID WHERE DEPARTMENTNAME = 'COMPUTER'